# Databricks notebook source
# MAGIC %md
# MAGIC # 00 - Config
# MAGIC Run this notebook first (or `%run` it from the other notebooks) to set up
# MAGIC the catalog/schema/volume and shared path variables.
# MAGIC
# MAGIC Works on both a Unity Catalog workspace and **Databricks Community Edition**
# MAGIC (which does not support catalogs/volumes) — just flip `USE_UNITY_CATALOG`
# MAGIC below and set `BASE_PATH` to wherever you uploaded `datasets/`.

# COMMAND ----------

USE_UNITY_CATALOG = True   # False on Community Edition / any workspace without UC

if USE_UNITY_CATALOG:
    CATALOG = "retail_demo"
    CATALOG_PREFIX = f"{CATALOG}."          # 3-part names: retail_demo.raw.bronze_orders
    RAW_SCHEMA, SILVER_SCHEMA, GOLD_SCHEMA = "raw", "silver", "gold"
    BASE_PATH = "/Volumes/retail_demo/raw/retail_files/retail_delta_project"
else:
    CATALOG = None
    CATALOG_PREFIX = ""                     # 2-part names: retail_demo_raw.bronze_orders
    RAW_SCHEMA, SILVER_SCHEMA, GOLD_SCHEMA = "retail_demo_raw", "retail_demo_silver", "retail_demo_gold"
    # Set this to wherever the Upload UI / dbutils.fs.cp put your datasets/ folder,
    # e.g. "dbfs:/FileStore/retail_delta_project" or "/FileStore/tables/retail_delta_project"
    BASE_PATH = "dbfs:/FileStore/retail_delta_project"

BATCH_PATH = f"{BASE_PATH}/datasets/batch"
INCR_PATH = f"{BASE_PATH}/datasets/incremental"
CHECKPOINT_PATH = f"{BASE_PATH}/_checkpoints"
SCHEMA_PATH = f"{BASE_PATH}/_schemas"

# COMMAND ----------

# MAGIC %md
# MAGIC ### Create catalog / schemas / volume (run once)

# COMMAND ----------

if USE_UNITY_CATALOG:
    spark.sql(f"CREATE CATALOG IF NOT EXISTS {CATALOG}")
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{RAW_SCHEMA}")
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SILVER_SCHEMA}")
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{GOLD_SCHEMA}")
    spark.sql(f"CREATE VOLUME IF NOT EXISTS {CATALOG}.{RAW_SCHEMA}.retail_files")
else:
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {RAW_SCHEMA}")
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {SILVER_SCHEMA}")
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {GOLD_SCHEMA}")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Upload the dataset package
# MAGIC Upload the `datasets/` folder (generated by `generate_datasets.py`) so it
# MAGIC lands at `BASE_PATH/datasets/...`.
# MAGIC - **Unity Catalog**: Catalog Explorer -> `retail_demo.raw.retail_files` -> Upload to this volume,
# MAGIC   or `databricks fs cp -r ./retail_delta_project/datasets dbfs:/Volumes/retail_demo/raw/retail_files/retail_delta_project/datasets`
# MAGIC - **Community Edition**: Data -> Add Data -> Upload File (or drag the folder in
# MAGIC   the Catalog UI's DBFS browser), then update `BASE_PATH` above to match
# MAGIC   whatever path it reports back.

# COMMAND ----------

dbutils.fs.mkdirs(CHECKPOINT_PATH)
dbutils.fs.mkdirs(SCHEMA_PATH)
print("BASE_PATH:", BASE_PATH)
print("BATCH_PATH:", BATCH_PATH)
print("INCR_PATH:", INCR_PATH)
display(dbutils.fs.ls(BASE_PATH))
