"""
Part 1: Data Generation
------------------------
Generates 4 CSV files with realistic, intentionally-messy e-commerce data:
    - customers.csv   (600 rows)
    - products.csv    (150 rows)
    - orders.csv      (1200 rows)
    - order_items.csv (2500 rows)

Intentional data quality issues (as required by the assignment):
    - 5% of orders have NULL customer_id
    - 3% of order_items have negative quantity (returns)
    - Some orders have order_date in wrong format (DD-MM-YYYY instead of YYYY-MM-DD HH:MM:SS)
    - Some product names have extra spaces / inconsistent casing
    - 2% of customer emails are invalid (missing @ or domain)

Referential integrity note (see "Think about" prompt in the assignment):
    Every order_id used in order_items.csv is generated by FIRST creating all
    orders, collecting their order_ids into a list, and THEN sampling from
    that list when building order_items. This guarantees every order_item
    references a real order. To let Part 2 / check_referential_integrity()
    actually have something to catch, we deliberately inject a small number
    of "orphan" order_items rows that reference order_ids that were never
    generated (simulating a real-world data pipeline glitch).
"""

import csv
import random
from datetime import datetime, timedelta

random.seed(42)  # reproducible fake data

OUT_DIR = "data"

# ---------------------------------------------------------------------------
# Reference data used to build realistic-looking rows without external libs
# ---------------------------------------------------------------------------

FIRST_NAMES = [
    "Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai", "Reyansh", "Krishna",
    "Ishaan", "Rohan", "Ananya", "Diya", "Aadhya", "Saanvi", "Myra", "Pari",
    "Anika", "Navya", "Kiara", "Riya", "James", "John", "Robert", "Michael",
    "William", "Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Wei",
    "Ming", "Hiro", "Yuki", "Chen", "Fatima", "Ahmed", "Omar", "Layla", "Zara",
]
LAST_NAMES = [
    "Sharma", "Verma", "Gupta", "Patel", "Kumar", "Singh", "Reddy", "Rao",
    "Mehta", "Joshi", "Smith", "Johnson", "Williams", "Brown", "Jones",
    "Garcia", "Miller", "Davis", "Wang", "Li", "Zhang", "Khan", "Ali",
    "Hassan", "Kim", "Park", "Nakamura", "Tanaka",
]

EMAIL_DOMAINS = ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com", "example.com"]

CUSTOMER_TYPES = ["REGULAR", "PREMIUM", "VIP"]
CUSTOMER_TYPE_WEIGHTS = [0.7, 0.22, 0.08]

ORDER_STATUSES = ["PLACED", "SHIPPED", "DELIVERED", "CANCELLED", "RETURNED"]
ORDER_STATUS_WEIGHTS = [0.10, 0.15, 0.55, 0.10, 0.10]

REGION_CODES = ["NORTH", "SOUTH", "EAST", "WEST", "CENTRAL"]

CATEGORIES = {
    "Electronics": ["Mobiles", "Laptops", "Audio", "Accessories", "Cameras"],
    "Clothing": ["Men", "Women", "Kids", "Footwear", "Winterwear"],
    "Home": ["Kitchen", "Furniture", "Decor", "Bedding", "Cleaning"],
    "Books": ["Fiction", "Non-Fiction", "Academic", "Comics", "Children"],
}

PRODUCT_NOUNS = [
    "Wireless Earbuds", "Smartphone", "Laptop Bag", "Bluetooth Speaker", "Smart Watch",
    "Cotton T-Shirt", "Denim Jeans", "Running Shoes", "Winter Jacket", "Kids Hoodie",
    "Non-Stick Pan", "Wooden Chair", "Wall Clock", "Bedsheet Set", "Vacuum Cleaner",
    "Mystery Novel", "Cook Book", "Comic Bundle", "Kids Storybook", "History Textbook",
    "USB Cable", "Power Bank", "Desk Lamp", "Yoga Mat", "Coffee Mug",
]

RNG = random.Random(42)

N_CUSTOMERS = 600
N_PRODUCTS = 150
N_ORDERS = 1200
N_ORDER_ITEMS = 2500

START_DATE = datetime(2023, 1, 1)
END_DATE = datetime(2025, 12, 31)


def random_date(start, end):
    delta = end - start
    seconds = RNG.randint(0, int(delta.total_seconds()))
    return start + timedelta(seconds=seconds)


def maybe_messy_email(name, idx):
    """2% of emails are invalid (missing @ or domain)."""
    local = name.lower().replace(" ", ".") + str(idx)
    if RNG.random() < 0.02:
        variant = RNG.choice(["no_at", "no_domain"])
        if variant == "no_at":
            return f"{local}{RNG.choice(EMAIL_DOMAINS)}"       # missing @
        else:
            return f"{local}@"                                  # missing domain
    return f"{local}@{RNG.choice(EMAIL_DOMAINS)}"


# ---------------------------------------------------------------------------
# 1. customers.csv
# ---------------------------------------------------------------------------

def generate_customers():
    rows = []
    for cid in range(1, N_CUSTOMERS + 1):
        first = RNG.choice(FIRST_NAMES)
        last = RNG.choice(LAST_NAMES)
        name = f"{first} {last}"
        reg_date = random_date(START_DATE, END_DATE)
        rows.append({
            "customer_id": cid,
            "customer_name": name,
            "email": maybe_messy_email(name, cid),
            "registration_date": reg_date.strftime("%Y-%m-%d %H:%M:%S"),
            "customer_type": RNG.choices(CUSTOMER_TYPES, weights=CUSTOMER_TYPE_WEIGHTS)[0],
        })

    with open(f"{OUT_DIR}/customers.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "customer_id", "customer_name", "email", "registration_date", "customer_type"
        ])
        writer.writeheader()
        writer.writerows(rows)

    print(f"customers.csv written: {len(rows)} rows")
    return rows


# ---------------------------------------------------------------------------
# 2. products.csv
# ---------------------------------------------------------------------------

def messy_product_name(base_name):
    """Some product names should have extra spaces or mixed case."""
    if RNG.random() < 0.15:
        variant = RNG.choice(["upper", "lower", "extra_spaces", "leading_trailing"])
        if variant == "upper":
            return base_name.upper()
        elif variant == "lower":
            return base_name.lower()
        elif variant == "extra_spaces":
            return "  ".join(base_name.split(" "))
        else:
            return f"  {base_name}  "
    return base_name


def generate_products():
    rows = []
    for pid in range(1, N_PRODUCTS + 1):
        category = RNG.choice(list(CATEGORIES.keys()))
        subcategory = RNG.choice(CATEGORIES[category])
        base_name = f"{RNG.choice(PRODUCT_NOUNS)} {RNG.choice(['Pro', 'Lite', 'Max', 'Plus', 'Classic', ''])}".strip()
        cost_price = round(RNG.uniform(50, 15000), 2)
        rows.append({
            "product_id": pid,
            "product_name": messy_product_name(base_name),
            "category": category,
            "subcategory": subcategory,
            "cost_price": cost_price,
        })

    with open(f"{OUT_DIR}/products.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "product_id", "product_name", "category", "subcategory", "cost_price"
        ])
        writer.writeheader()
        writer.writerows(rows)

    print(f"products.csv written: {len(rows)} rows")
    return rows


# ---------------------------------------------------------------------------
# 3. orders.csv
# ---------------------------------------------------------------------------

def format_order_date(dt, wrong_format=False):
    if wrong_format:
        return dt.strftime("%d-%m-%Y")  # missing time, wrong separator/order
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def generate_orders(customers):
    rows = []
    customer_ids = [c["customer_id"] for c in customers]

    for oid in range(1, N_ORDERS + 1):
        dt = random_date(START_DATE, END_DATE)

        # 5% of orders have NULL customer_id
        if RNG.random() < 0.05:
            cust_id = ""  # empty -> treated as NULL
        else:
            cust_id = RNG.choice(customer_ids)

        # Some orders have order_date in wrong format (DD-MM-YYYY)
        wrong_format = RNG.random() < 0.08

        rows.append({
            "order_id": oid,
            "customer_id": cust_id,
            "order_date": format_order_date(dt, wrong_format),
            "status": RNG.choices(ORDER_STATUSES, weights=ORDER_STATUS_WEIGHTS)[0],
            "region_code": RNG.choice(REGION_CODES),
        })

    with open(f"{OUT_DIR}/orders.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "order_id", "customer_id", "order_date", "status", "region_code"
        ])
        writer.writeheader()
        writer.writerows(rows)

    print(f"orders.csv written: {len(rows)} rows")
    return rows


# ---------------------------------------------------------------------------
# 4. order_items.csv
# ---------------------------------------------------------------------------

def generate_order_items(orders, products):
    rows = []
    order_ids = [o["order_id"] for o in orders]
    product_ids = [p["product_id"] for p in products]

    # Reserve a small number of "orphan" order_ids that do NOT exist in
    # orders.csv, to intentionally break referential integrity so that
    # check_referential_integrity() in Part 2 has something real to find.
    orphan_order_ids = [N_ORDERS + i for i in range(1, 16)]  # 15 orphan ids

    item_id = 1
    n_orphan_rows = 20  # ~0.8% of rows reference non-existent orders

    for _ in range(N_ORDER_ITEMS - n_orphan_rows):
        order_id = RNG.choice(order_ids)
        product_id = RNG.choice(product_ids)
        quantity = RNG.randint(1, 6)

        # 3% of order_items have negative quantity (these are returns)
        if RNG.random() < 0.03:
            quantity = -quantity

        unit_price = round(RNG.uniform(50, 15000), 2)
        discount_percent = RNG.choice([0, 0, 0, 5, 10, 15, 20, 25, 30, 50])

        rows.append({
            "item_id": item_id,
            "order_id": order_id,
            "product_id": product_id,
            "quantity": quantity,
            "unit_price": unit_price,
            "discount_percent": discount_percent,
        })
        item_id += 1

    # Add the orphan rows (bad referential integrity, on purpose)
    for _ in range(n_orphan_rows):
        rows.append({
            "item_id": item_id,
            "order_id": RNG.choice(orphan_order_ids),
            "product_id": RNG.choice(product_ids),
            "quantity": RNG.randint(1, 4),
            "unit_price": round(RNG.uniform(50, 15000), 2),
            "discount_percent": RNG.choice([0, 10, 20]),
        })
        item_id += 1

    RNG.shuffle(rows)
    # re-sequence item_id after shuffle so ids stay unique/sequential
    for i, row in enumerate(rows, start=1):
        row["item_id"] = i

    with open(f"{OUT_DIR}/order_items.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "item_id", "order_id", "product_id", "quantity", "unit_price", "discount_percent"
        ])
        writer.writeheader()
        writer.writerows(rows)

    print(f"order_items.csv written: {len(rows)} rows")
    return rows


if __name__ == "__main__":
    import os
    os.makedirs(OUT_DIR, exist_ok=True)

    customers = generate_customers()
    products = generate_products()
    orders = generate_orders(customers)
    order_items = generate_order_items(orders, products)

    print("\nAll 4 CSV files generated successfully in ./data/")
